name: deploy to gae

on:
  push:
    branches:
      - main


jobs:
  deploy_gae:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'      
      - name: List Files and Folders
        run: |
          ls -al    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  
         
      - name: Terraform Format
        run: terraform fmt
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}  

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_CREDS }}
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json:  ${{ secrets.GOOGLE_SA_CREDS }}
          
      - name: Login to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev          
         
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/gcpa-415907/app-engine/daily_quote:latest
          



          



          
